Removed double memory allocation in __clove_path_basepath
fdefelici/clove-unit pull request #63
Opened 2023-10-12 20:36 UTC by vonhoff

Fix #62 
- Added unit tests based on the previous implementation to ensure original functionality.
- Removed usage of `__clove_string_strdup` in `__clove_path_basepath`.

2023-10-13 05:07 UTC, fdefelici commented
The allocation has been reduced to one, but probably we loose clarity with a more algorithm approach.

Considering that the function is not critical for performance I'd prefer an approach that favor code readability (and then if with just one alloc, better :))

2023-10-13 09:05 UTC, vonhoff commented
Another solution I had in mind would be the following, I have tried to make it a bit clearer and more readable. It may still be algorithmic, but I'm out of ideas. 
```
char* __clove_path_basepath(const char* a_path) {
    // Find the last path separator character in the input path.
    const char* last_char = a_path + strlen(a_path) - 1U;
    while (last_char > a_path && *last_char != '/' && *last_char != '\\') {
        --last_char;
    }

    // If there are no separators in the path, return the current directory path.
    if (last_char == a_path) {
        static char dot_path[3] = { '.', __CLOVE_PATH_SEPARATOR, '\0' };
        return strdup(dot_path);
    }

    size_t base_length = last_char - a_path;
    char* base_path = __CLOVE_MEMORY_CALLOC_TYPE_N(char, base_length + 1);
    memcpy(base_path, a_path, base_length);

    // Replace any '/' or '\\' characters in the base path with the appropriate path separator.
    for (size_t i = 0; i < base_length; i++) {
        if (base_path[i] == '/' || base_path[i] == '\\') {
            base_path[i] = __CLOVE_PATH_SEPARATOR;
        }
    }

    return base_path;
}
```

2023-10-13 19:48 UTC, fdefelici commented
Second solution seems better.

I suggest to use some clove apis:
- __clove_memory_memcpy
- __clove_string_replace_char
- __clove_string_length

Note: Eventually we could wrap the two calls to `__clove_string_replace_char` into a new function `__clove_path_to_os(char*)`. 
We could use this new function instead of #ifdef in unit test to obtain expected paths for assertion.

2023-10-21 09:43 UTC, vonhoff commented
Apologies for the delay; I was on a break. I've now revised the code and added relevant unit tests.

2023-10-21 15:19 UTC, fdefelici requested changes
I was imaging __clove_path_to_os like this: `void __clove_path_to_os(char*)`
to avoid allocation. Then in future if we need to keep the original string from modification we could implement a dedicated function.

2023-10-21 15:32 UTC, fdefelici requested changes
In the unit tests we could definitely avoid #ifdef. Just wr

2023-10-21 15:32 UTC, fdefelici commented on clove-unit.h
> +    const char* last_char = a_path + strlen(a_path) - 1U;
here we could use `__clove_string_length`  instead of native strlen

2023-10-21 15:32 UTC, fdefelici commented on clove-unit.h
> +__CLOVE_EXTERN_C char* __clove_path_to_os(const char* path);
for now a `void __clove_path_to_os(char*)` could do the job, avoiding allocation

2023-10-21 17:58 UTC, vonhoff commented
I applied the requested changes

2023-10-22 09:10 UTC, fdefelici approved these changes

2023-10-22 10:33 UTC, merged